brew "eza"
brew "fish"
brew "fnm"
brew "fzf"
brew "git-delta"
brew "git-lfs"
brew "jq"
brew "neovim"
brew "ripgrep"
brew "starship"
brew "stow"
brew "tree-sitter-cli"

cask "dotnet-sdk"
cask "dotnet-sdk@8"
cask "font-fira-code-nerd-font"
cask "ghostty"
