#!/bin/bash
shopt -s dotglob
LOCATION="$HOME/Computer/dotfiles"
DOTFILES="$LOCATION/config"
FILE="$LOCATION/dotlist.txt"

# create dotlist
init() {
    if [ ! -f "$FILE" ]; then
        touch "$FILE"
    fi
}

handleFile() {
    init
    IFS=' '
    while read -ra line; do
        if [ "$2" == "link" ]; then
            ln -sf "$DOTFILES/${line[0]}" "$HOME/${line[1]}"
        else
            cp -f "$DOTFILES/${line[0]}" "$HOME/${line[1]}"
        fi
    done <"$FILE"
}

add() {
    # not working needs fixing
    if [ "$1" == "" ] || [ ! -e "$1" ]; then
        exit 1
    fi

    init
    TARGET=$(basename "$1")
    DOTSOURCE="$PWD/$TARGET"
    DOTTARGET="$(echo "$PWD/${TARGET#.}" | cut -d'/' -f5-)"
    if [ "$DOTTARGET" == "" ]; then
        DOTTARGET="$TARGET"
    fi
    mkdir -p "$(dirname "$DOTFILES/$DOTTARGET")"
    mv "$DOTSOURCE" "$_"
    ln -sf "$DOTFILES/$DOTTARGET" "$DOTSOURCE"
    echo "$DOTTARGET $(echo "$DOTSOURCE" | cut -d'/' -f4-)" >>"$FILE"
}

remove() {
    link="$(readlink "$1")"
    directory="$(dirname "$1")"
    mv -f "$link" "$directory"
    # add support for removing directory if it is empty
}

list() {
    # chesk for dotfiles in dir that are not tracked and that are present but not nexistent
    # Missing : ...
    # Untracked : ...
    while read -ra line; do
        echo "$(basename "${line[0]}")"
    done <"$FILE"
}

# todo add list functionality that lists all currently tracked dotfiles and remove that removes tracking

case "${1}" in
"link")
    handleFile "" "link"
    ;;
"copy")
    handleFile "" "copy"
    ;;
"help")
    printf "link - creates links \ncopy - copies files\n"
    ;;
    #"add")
    #    add "$2"
    #    ;;
    #"remove")
    #    remove "$2"
    #    ;;
"list")
    list ""
    ;;
*)
    echo "Invalid input, use help"
    ;;
esac
