#!/bin/bash
LOCATION="$(dirname -- $(readlink -f ${BASH_SOURCE}))"
DOTFILES="$LOCATION/config"
FILE="$LOCATION/dotlist.txt"

echo $LOCATION

IFS=' '
    while read -r from to; do
        echo "$from -> $to"
        mkdir -p "$(dirname $HOME/$to)"
        ln -sf "$DOTFILES/$from" "$HOME/$to"
    done <"$FILE"
